name = "github-repo-library"
compatibility_date = "2024-01-01"

[site]
bucket = "."

[[pages_build_output_dir]]
value = "."

[build]
command = ""
cwd = ""
watch_dir = ""

[env.production]
name = "github-repo-library"
